version:  '3'

services:
##############################################################
#         Setup node container
##############################################################

  backend:
    build: ./backend
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      DB_CONNECTION: ${DB_CONNECTION}
    ports:
    - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
    - ./backend/:/srv/app/wildcard-backend/
    command: npm run dev

##############################################################
#         Setup client container
##############################################################

  frontend:
    build: ./frontend
    expose:
      - ${REACT_APP_PORT}
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
    ports:
    - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
    - ./frontend/src:/srv/app/wildcard-front/src
    - ./frontend/public:/srv/app/wildcard-front/public
    links:
      - backend
    command: sh -c "npm install && npm run build && npm start"

