version:  '3'



services:
  ##############################################################
#         Setup node container
##############################################################

  backend:
    build: ./backend
    expose:
      - 8080
    environment:
      APP_SERVER_PORT: 8000
    ports:
        - 8080:8080
    volumes:
        - ./backend/:/srv/app/wildcard-backend/
    command: sh -c "npm install && npm run dev"

##############################################################
#         Setup client container
##############################################################

  frontend:
    build: ./frontend
    expose:
      - 3000
    environment:
      REACT_APP_PORT: 3000
    ports:
    - 3000:3000
    volumes:
    - ./frontend/src:/srv/app/wildcard-front/src
    - ./frontend/public:/srv/app/wildcard-front/public
    depends_on:
      - backend
    command: sh -c "npm install && npm start"
