version:  '3'

volumes:
  frontend-volume:

services:
##############################################################
#         Setup client container
##############################################################

  frontend:
    build: ./frontend
    expose:
      - 3000
    environment:
      REACT_APP_PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - frontend-volume:/srv/app/wildcard-front/
    depends_on:
      - backend
    command: sh -c "npm install && npm run build"


  ##############################################################
#         Setup node container
##############################################################
  backend:
    build: ./backend
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
    - ./backend/:/srv/app/wildcard-backend/
    - frontend-volume:/srv/app/wildcard-front/
    command: sh -c "npm start"

