version:  '3'

services:
  ##############################################################
  #         Setup mongo container
  ##############################################################
  mongodb:
    image: mongo
    restart: always
    container_name: mongodbWild
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth

  ##############################################################
#         Setup node container
##############################################################

  backend:
    build: ./backend
    expose:
      - 8000
    environment:
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      DB_CONNECTION: ${DB_CONNECTION}
    ports:
    - 8000:8000
    depends_on:
        - mongodb
    volumes:
    - ./backend/:/srv/app/wildcard-backend/
    command: npm run dev

##############################################################
#         Setup client container
##############################################################

  frontend:
    build: ./frontend
    expose:
      - 3000
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
    ports:
    - 3000:3000
    volumes:
    - ./frontend/src:/srv/app/wildcard-front/src
    - ./frontend/public:/srv/app/wildcard-front/public
    depends_on:
      - backend
    command: sh -c "npm install && npm start"

